import {
    faBed,
    faBicycle,
    faCamera,
    faCar,
    faChartBar,
    faCoins,
    faCreditCard,
    faDesktop,
    faDollarSign,
    faFileInvoice,
    faGamepad,
    faGasPump,
    faGlassCheers,
    faGlobe,
    faHeadphones,
    faMapMarkedAlt,
    faMobileAlt,
    faMoneyBill,
    faMotorcycle,
    faPlane,
    faReceipt,
    faShoppingBag,
    faShoppingCart,
    faSubway,
    faSuitcase,
    faTaxi,
    faTrain,
    faTree,
    faTshirt,
    faUtensils,
    faWallet
  } from '@fortawesome/free-solid-svg-icons';

export const icons = [
    { iconName: 'Bed', icon: faBed },
    { iconName: 'Bicycle', icon: faBicycle },
    { iconName: 'Camera', icon: faCamera },
    { iconName: 'Car', icon: faCar },
    { iconName: 'ChartBar', icon: faChartBar },
    { iconName: 'Coins', icon: faCoins },
    { iconName: 'CreditCard', icon: faCreditCard },
    { iconName: 'Desktop', icon: faDesktop },
    { iconName: 'DollarSign', icon: faDollarSign },
    { iconName: 'FileInvoice', icon: faFileInvoice },
    { iconName: 'Gamepad', icon: faGamepad },
    { iconName: 'GasPump', icon: faGasPump },
    { iconName: 'GlassCheers', icon: faGlassCheers },
    { iconName: 'Globe', icon: faGlobe },
    { iconName: 'Headphones', icon: faHeadphones },
    { iconName: 'MapMarkedAlt', icon: faMapMarkedAlt },
    { iconName: 'MobileAlt', icon: faMobileAlt },
    { iconName: 'MoneyBill', icon: faMoneyBill },
    { iconName: 'Motorcycle', icon: faMotorcycle },
    { iconName: 'Plane', icon: faPlane },
    { iconName: 'Receipt', icon: faReceipt },
    { iconName: 'ShoppingBag', icon: faShoppingBag },
    { iconName: 'ShoppingCart', icon: faShoppingCart },
    { iconName: 'Subway', icon: faSubway },
    { iconName: 'Suitcase', icon: faSuitcase },
    { iconName: 'Taxi', icon: faTaxi },
    { iconName: 'Train', icon: faTrain },
    { iconName: 'Tree', icon: faTree },
    { iconName: 'Tshirt', icon: faTshirt },
    { iconName: 'Utensils', icon: faUtensils },
    { iconName: 'Wallet', icon: faWallet },
];
